import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Contactship",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="px-4 font-sans min-h-screen grid grid-rows-[auto,1fr,auto] antialiased
      max-w-2xl mx-auto"
      >
        <header className="text-2xl font-bold leading-[4rem]">Contactship</header>
        {children}
        <footer className="text-center leading-[4rem] opacity-70"> © by Kevoff</footer>
      </body>
    </html>
  );
}
